// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 03.07.2025 11:00:33
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ercan/OneDrive/Desktop/ai/last_24/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/ai/last_24/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/ai/last_24/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/ai/last_24/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/ai/last_24/plugins/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/ai/last_24/composables/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/ai/last_24/utils/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/ai/last_24/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/ai/last_24/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/ai/last_24/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/ai/last_24/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;