// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 03.07.2025 12:45:55
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ercan/OneDrive/Desktop/last_28/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/last_28/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/last_28/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/last_28/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/last_28/plugins/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/last_28/composables/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/last_28/utils/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/last_28/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/last_28/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/last_28/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/last_28/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;